### ISSUE TITLE
庄崎君のサーバーをMac上に立てる

### ISSUE THREAD

**Issue by yanoty3d** [smalab/ScoreServer#1]
庄崎君のサーバーを、スマラボのMacで使えるようにする。

**Comment by yanoty3d** [comment]
n

**Comment by oitsmalab** [comment]
テーブル：Ｓｕｍａを追加して、動作確認完了。
スマラボのＭａｃから庄崎君のＭａｃにアクセス確認。
スマラボＭａｃからスコアを庄崎君のＭａｃに転送して保存完了。
