### ISSUE TITLE
イベントのデータの解析と、結果の文書化

### ISSUE THREAD

**Issue by yanoty3d** [smalab/ScoreServer#11]
TAMによる8月のイベントでの解析と、得られる結果を文書に残す
- [x] データ
- [x]  手順（サンプルと同じなら、省略してよい）
- [x]  結果

**Comment by oitsmalab** [comment]
https://drive.google.com/open?id=0B1IUVPG3GzFAcDEwaU9JTnJpQXc
CSV形式のデータファイルまとめ

**Comment by oitsmalab** [comment]
https://drive.google.com/open?id=0B1IUVPG3GzFAVFNlRTJ4MWdCWEk
解析結果まとめ（教文事後易、教文事前以外）

**Comment by yanoty3d** [comment]
だれも解けていない問題は、解析できないので除外する。
うめきた・教文を別に解析したものと、一緒に解析したものを用意する。
うめきたはすでに完成
教文は、一部問題を除外して解析

**Comment by oitsmalab** [comment]
完成したのでコミットしました。[@b748ea7]
