### ISSUE TITLE
2PL、3PLのスコア計算サンプルを作る

### ISSUE THREAD

**Issue by yanoty3d** [smalab/ScoreServer#4]
Excelで2PL、3PLのスコア計算を実現させる。

**DOD**
- [ ] ２PLモデルについて、エクセルファイルを用いて、解答パターンからスコアを計算できる。
- [ ] ３PLモデルについて、エクセルファイルを用いて、解答パターンからスコアを計算できる。

**Comment by yanoty3d** [comment]
@5fe682f55c3ff4d9d17971cddc4c36e2156103f0
θの計算方法を決める。

**Comment by yanoty3d** [comment]
計算モデルから、スコアを計算するサンプルをつくる。

**Comment by yanoty3d** [comment]
Estimateを8に決定。

**Comment by oitsmalab** [comment]
Rを用いて同時最尤推定法の測定に移行するためＣｌｏｓｅする。
