### ISSUE TITLE
英語学力テストのサンプル

### ISSUE THREAD

**Issue by yanoty3d** [smalab/ScoreServer#5]
イベントの最初に子供たちの学力を測定できる、英語ペーパーテスト（５分程度）をつくる。
それらの正誤から、項目反応理論にもとづいてスコアを計算できるようにする。

**DOD**
- [x] 子供が5分程度で解答できる英語テストが完成。
- [x] エクセルの手入力で良いので、各個人が自分のテストの採点結果からスコアを計算できるようにする。

**Comment by yanoty3d** [comment]
Estimate を５に決定。

**Comment by oitsmalab** [comment]
問題サンプル1つ完成

**Comment by oitsmalab** [comment]
選択式の問題に変更すること

**Comment by oitsmalab** [comment]
https://docs.google.com/document/d/1WzF4zeYswqZwtbmXQxPN0PP35VGzpVHgeA-A22rA9CE/edit?usp=sharing

**Comment by oitsmalab** [comment]
https://docs.google.com/document/d/1XiKdGQ8VMG9WXwjuWh3TKU5FYcOwi4OtTx4NjUU5utc/edit?usp=sharing

**Comment by oitsmalab** [comment]
選択式にして再度リンクを貼る

**Comment by oitsmalab** [comment]
https://docs.google.com/document/d/1WzF4zeYswqZwtbmXQxPN0PP35VGzpVHgeA-A22rA9CE/edit?usp=sharing
https://docs.google.com/document/d/1XiKdGQ8VMG9WXwjuWh3TKU5FYcOwi4OtTx4NjUU5utc/edit?usp=sharing
修正を加えた問題サンプルです。

**Comment by oitsmalab** [comment]
うめきたの回答サンプルをもとにＲのＴＡＭサンプルを用いて同時最尤測定法で測定する。
Ｒへ移行するためＣｌｏｓｅする
