### ISSUE TITLE
RのTAMパッケージを用いて、同時最尤推定法でスコア計算を行う

### ISSUE THREAD

**Issue by yanoty3d** [smalab/ScoreServer#7]
英語サンプルテストのスコアから、RのTAMパッケージでスコア計算を行う。

**Comment by yanoty3d** [comment]
各問題の正答率から

問題の難しさ
被験者の能力

**Comment by yanoty3d** [comment]
- [x] TAMパッケージ用のサンプルデータの用意
- [ ] うめきたイベントで得られたデータを、TAM用に加工して読めることを確認する

**Comment by oitsmalab** [comment]
https://rstudio-pubs-static.s3.amazonaws.com/69226_3f20cd8a33e14b81923576ed1f2426d3.html
Ｒの参考サイト

**Comment by oitsmalab** [comment]
> dat <- read.csv(”C:/Users/smalab/Desktop/ファイル名", header = T, sep=",", na.strings="NA", dec=".", strip.white=TRUE, fileEncoding = "CP932")
> 上でデータの入力が可能

**Comment by oitsmalab** [comment]
https://docs.google.com/spreadsheets/d/14NFixW387UsmQC5GUlIscgmQQhfiYfWPJuILtz6Gj3U/edit?usp=sharing
https://docs.google.com/spreadsheets/d/1Qd4cy1a2kRpiPljbD3HF24QxYmrYuI3JInjCZMItGro/edit?usp=sharing
8月１日うめきた算数英語教室のデータ集計

**Comment by oitsmalab** [comment]
Rで同時最尤法を使い、測定しようとしたがファイルの拡張子が合わず、実行できない。変換が可能なプログラムが必要
xlsxからcsv

**Comment by oitsmalab** [comment]
ｘｌｓｘからｃｓｖへの変化に成功。
ひら、カナ、漢字の使用可、空白の使用可。
名前欄で複数の文字種を使用すると文字列が乱れる可能性あり。
空白キーを使って文字列の調整は不可。

**Comment by oitsmalab** [comment]
Rの実行可能な条件
問題数は8まで
人数は上限なし？（204人まで確認済み）
問題、人の名前に英語である規制なし
連続して同じ回答の人がいた場合、省略される。（違う名前でも）
http://127.0.0.1:18738/library/TAM/html/tam.jml.html　（TAMパッケージ内のtam.jml関数について）
observedも変更可能

**Comment by oitsmalab** [comment]
Rパッケージ編集方法参考サイト
http://nakhirot.hatenablog.com/entry/20130627/1372341785
＊Linux上での話
DL→解答→編集→圧縮→インストール？

**Comment by yanoty3d** [comment]
7zipで解凍するとよいかも。現在はラプラスを使用中
