### ISSUE TITLE
うめきたさんすう・えいご教室で、英語のテストを行い、得点を集計する

### ISSUE THREAD

**Issue by yanoty3d** [smalab/ScoreServer#8]
事前テスト
学力の計測に使う。アルファベットの知識により、未経験者と初心者に分ける。
https://drive.google.com/open?id=1WzF4zeYswqZwtbmXQxPN0PP35VGzpVHgeA-A22rA9CE

事後テスト
初心者テスト
https://drive.google.com/open?id=1XiKdGQ8VMG9WXwjuWh3TKU5FYcOwi4OtTx4NjUU5utc

未経験者テストが無いので、早急に作成する

**Comment by yanoty3d** [comment]
参加者の各問題への正答、誤答の集計
各問題について正答率の計算の集計
　　　　　　　問題１　問題２　、、、　総得点　　
参加者１　　○　　　　　×　　　　　　　　５４
参加者２　　×　　　　　○　　　　　　　　２９　
、、、
平均正答率　25%   40%

**Comment by oitsmalab** [comment]
https://drive.google.com/open?id=14NFixW387UsmQC5GUlIscgmQQhfiYfWPJuILtz6Gj3U  事前
https://drive.google.com/open?id=1Qd4cy1a2kRpiPljbD3HF24QxYmrYuI3JInjCZMItGro　事後
うめきたの集計結果

**Comment by oitsmalab** [comment]
https://drive.google.com/open?id=1vrYJKaYv3QOSJJ2i82BUMTS35Xmp_nWqCpPgzFrqN2s 　事前
https://drive.google.com/open?id=19Q6jlXOnF3nPQKx65H9Mv3NacGvqKGzzqKC2OiUJNFI 事後
教文の集計結果
