### ISSUE TITLE
 TAMパッケージを修正し、9問以上の問題を解析できる

### ISSUE THREAD

**Issue by yanoty3d** [smalab/ScoreServer#9]
現状では8問しか解析できないので、9問以上解析できるようパッケージを修正する
- [ ] 9問以上あるサンプルデータ
- [ ] 9問以上あるサンプルデータの解析結果

**Comment by oitsmalab** [comment]
パッケージの修正方法についてはでてこなかったが、Rのパッケージ作成についての記述があったのでリンクをのせておく。
https://cran.r-project.org/doc/contrib/manuals-jp/R-exts.jp.pdf

**Comment by oitsmalab** [comment]
http://www.okadajp.org/RWiki/?R%E3%81%A7%E9%A0%85%E7%9B%AE%E5%8F%8D%E5%BF%9C%E7%90%86%E8%AB%96#s5504cb5
Rでの実行例など詳しく紹介してくれているが、パッケージなどのソースがない。

**Comment by oitsmalab** [comment]
今使っているTAMパッケージと同じ方法(　library(ltm)　)でパッケージのインストールはできる。実行例の元データはhttp://www.asakura.co.jp/books/isbn/978-4-254-12795-9/より。

**Comment by yanoty3d** [comment]
問題数は関係なく、だれも解けていない問題を除外すればよい。
